# Generated by Django 5.0.6 on 2024-05-12 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=12, unique=True)),
                ('capacity', models.IntegerField(help_text='35 - 55', validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(55)])),
            ],
            options={
                'verbose_name': 'bus',
                'verbose_name_plural': 'buses',
                'db_table': 'bus',
            },
        ),
    ]
